---
- hosts: webservers
  become: true
  become_user: root
  tasks:    
  - name: Install pip
    apt: name=python3-pip state=present

  - name: install docker-py
    pip: name=docker-py

  - name: Running the container
    docker_container:
     name: neww
     image: chetana3/project:$build_number
     ports:
      - "8085:80"
     state: started

  - name: Check if container is running
    shell: docker ps
